### ISSUE TITLE
Textractor x86 plugin not working

### ISSUE THREAD

**Issue by mobedoor** [fauu/Kamite#8]
Hi. The x86 plugin for Textractor does not work for me throwing the following error.
![1671028565](https://user-images.githubusercontent.com/71059800/207624505-05687fa8-0912-414f-a556-dfb2277a098a.png)
The 64 bit plugin works fine. Can you reproduce? 
OS: Endeavour OS

**Comment by fauu** [comment]
Thanks for letting me know anyway. There's no reason it shouldn't work with an alpha build, and if it doesn't, it might also not work with a new version once it's released. I'll look into it.

**Comment by fauu** [comment]
This only seems to happen on Wine and only for the x86 dll. A workaround is to build the x86 dll using mingw-w64 instead of zig (573b9979c0f67a3f595a802a35fc7506bf2c9e6a).

The working dll will be the default in the next version, but I also upload it here: [KamiteSend-x86-151222.zip](https://github.com/fauu/Kamite/files/10237224/KamiteSend-x86-151222.zip).

**Comment by mobedoor** [comment]
Works perfectly. Thank you for the prompt fix.
